### ISSUE TITLE
Support for Django 1.9

### ISSUE THREAD

**Issue by raphaelm** [swisscom/cleanerversion#111]
The first beta for Django 1.9 has just been released, no more features will come to 1.9, only bugs will be fixed. One could therefore start evaluating what needs to change in cleanerversion to support Django 1.9.

At a first look, I noticed that some pretty things of the ORM implementation pretty essential to cleanerversion have been changed:
- `ValuesQuerySet` and `ValuesListQuerySet` have been removed.
- In `django.db.models.fields.related`, the members `ReverseSingleRelatedObjectDescriptor`, `ReverseManyRelatedObjectsDescriptor`, `ManyRelatedObjectsDescriptor`, `create_many_related_manager`, `ForeignRelatedObjectsDescriptor` have been refactored into new classes at `django.db.models.fields.related_descriptors`.

**Comment by raphaelm** [comment]
Django 1.9 has been released now :)

**Comment by raphaelm** [comment]
It seems like none of the descriptor classes vanished, but https://github.com/django/django/commit/e542e81b39e8610b70cf1d68f95ece0279028765 renamed them. I tried to adjust it myself, but I failed so far. For someone who actually understands how all this stuff works, it should not be too hard from the first look.

**Comment by maennel** [comment]
Hey @raphaelm, have you pushed your attempt to migrate to Django 1.9 already somewhere? Thanks

**Comment by raphaelm** [comment]
No, because I did not do much more than renaming the class imports according to the commit I referened above until there were no more "unresolved names" left, however, nothing worked at all. I threw it away for a second try that also did not work out.

**Comment by maennel** [comment]
So, I've created a [django19-compatibility branch](https://github.com/swisscom/cleanerversion/tree/django19-compatibility) already. For now, I've added the additional Django1.9 environments for testing (and removed the ones for Django1.6).
As expected (and reported), tests fail: https://travis-ci.org/swisscom/cleanerversion/branches

**Comment by maennel** [comment]
I'll close this issue, since we have introduced support for Django 1.9 and onwards. See #127 for more info.
