### ISSUE TITLE
Is there good way to reference specific version?

### ISSUE THREAD

**Issue by qrilka** [swisscom/cleanerversion#115]
It appears that `cleanerversion` allows only keys to the latest version of particular entity with `VersionedForeignKey` allowing to check version for specific time.
But what if I want to have a link to some specific version? E.g. I want to store the state of some entity just like it was at that particular time. I can't use id/identity as those get overriden. I could use id + datetime but that seems to work OK only for single entity and constructing 1 query to select some "events" with corresponding historical versions of objects those event were fired appears to be not a trivial task.
Is having something like this out of the scope of `cleanerversion` and I need to use something else?
Or I just miss something obvious?

**Comment by brki** [comment]
If you store someplace the identity and datetime, then you can at any later time get back to that object with something like:
```
entity = MyModel.objects.as_of(desired_datetime).get(identity=desired_identity)
```

And from this entity you can get all the related objects as they were at ``desired_datetime`` just by accessing them as you normally would with the Django ORM, for example:
```
entity.related_thing_set.all()
entity.related_fk_thing
```

If you want to query several entities *at different times* all in one query: no, that is not possible.  You'd need to construct a separate query for each different time.

**Comment by qrilka** [comment]
Yes, I was asking about 1 event log with events of different times looking at different versions of different objects.
Mutable history used in `cleanerversion` pays back at least for this scenario, ok I'll use something else, thank you
