### ISSUE TITLE
After 1.6.0 identity_shortener fails with 'UUID' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by s-m-b** [swisscom/cleanerversion#123]
With list_display_show_identity = True in admin

**Comment by brki** [comment]
The fix would be to add str() around object.identity at https://github.com/swisscom/cleanerversion/blob/87b0a3c7f8b5e755fc67670785016457325d4c12/versions/admin.py#L276 .

Adding a test would be nice.

**Comment by brki** [comment]
I assume that ``history_view()`` in admin.py also fails, since it calls ``unquote()``, which expects it's parameter to be a string.

**Comment by rossmechanic** [comment]
Any plans to fix this? Or to fix the history view?

**Comment by maennel** [comment]
From what I can see, @rossmechanic addressed this issue with #142 
Closing.
