### ISSUE TITLE
Doc misprint

### ISSUE THREAD

**Issue by tbazadaykin** [swisscom/cleanerversion#149]
I think that thare is some misprint in the documentation:

> If you really want to filter using the id of the object, you need to explicitly use the id instead of
> passing the object itself::
> 
>     >> stb5 = SportsClub.objects.as_of(t1).filter(discipline_id=running.id, name='STB').first()
>     >> stb6 = SportsClub.objects.as_of(t1).filter(discipline_id=running_at_t1.id, name='STB').first()
>     >> (stb5.discipline.id, stb6 is None)
>     (True, 2)
> 
>     >> stb7 = SportsClub.objects.current.filter(discipline_id=running.id, name='STB').first()
>     >> stb8 = SportsClub.objects.current.filter(discipline_id=running_at_t1.id, name='STB').first()
>     >> (stb7.discipline.id, stb8 is None)
>     (1, True)

It seems, that the first tuple should be `(2, True)`, not `(True, 2)`.

**Comment by maennel** [comment]
Agree - thanks for pointing out. Do you have time to create a PR for this? Thanks
