### ISSUE TITLE
How to clone the version when using Django Rest Framework?

### ISSUE THREAD

**Issue by simkimsia** [swisscom/cleanerversion#160]
I am using Django as a backend hence Django Rest Framework and its serializers are my choice.

Creation works so long as I add the following in the serializer.

```
    id = serializers.UUIDField(read_only=True)
    identity = serializers.UUIDField(read_only=True)
```

However, edit doesn't automatically trigger the clone. So how do I use CleanerVersion with DRF?

Django version: 1.11
DRF version: 3.7.7

**Comment by simkimsia** [comment]
Okay I figured out how do to this in DRF serializer

```
from rest_framework import serializers

class YourModelSerializer(serializers.Serializer)::
   ..
    id = serializers.UUIDField(read_only=True)
    identity = serializers.UUIDField(read_only=True)

    class Meta:
        model = YourModel
        name = 'your_model'
        fields = ('id',
                  'identity', ...)

    def update(self, instance, validated_data):
        instance = instance.clone()
        return super().update(instance, validated_data)
```

**Comment by maennel** [comment]
Indeed, you have to override the ``update`` method. We faced the same/a similar challenge and went one step further by even comparing whether there is a diff between the old version and the new version (i.e. whether the update really makes sense). 
This way you'd save some space if you expect many "dumb" updates.
