### ISSUE TITLE
Support for migrating an existing app to use CleanerVersion

### ISSUE THREAD

**Issue by danxshap** [swisscom/cleanerversion#164]
Hey all, I'm trying to migrate a single model in my existing app (Django 1.11 with Postgresql) to make it versionable, but I'm running into some database migration-related issues and I wanted to raise them to ask the CleanerVersion experts if I'm doing something wrong or if perhaps my use case simply isn't supported.

1. By default, CleanerVersion wants to migrate my existing model's `id` column from an integer field to a UUID field, but postgres won't allow casting between those types. I assumed that this meant I needed to set `VERSIONS_USE_UUIDFIELD = False`, so that's what I did to get past that -- is that the recommended approach in this case?
2. With the setting change I mentioned above, CleanerVersion wants to migrate my model's `id` field to a CharField, but this failed because there are multiple existing FKs pointing to this model (I changed them all to use `VersionedForeignKey` first, per the docs), so it violates the constraints in postgres because the existing FK fields are integer type columns (i.e. a different/incompatible type). I needed to manually drop all of the FK constraints for FKs pointing to this table in postgres in order to get the Django migrations to run successfully -- would this be expected, or is there perhaps some better way to do the initial migration?
3. Am I correct in understanding that, based on the line about M2M relationships in [this part of the docs](https://cleanerversion.readthedocs.io/en/latest/doc/historization_with_cleanerversion.html?highlight=migrate#integrating-cleanerversion-versioned-models-with-non-versioned-models), If I want to have a M2M relationship between 2 models, they _both_ must be versionable (or, of course, both not versionable)?
    - As I mentioned at the top, I'm just trying to make one model ("Model A") in my app versionable, but I have another model that has multiple M2M fields pointing to Model A, and when I try to clone an instance of Model A, I get a `DataError` because apparently CleanerVersion is trying to add non-integer values (e.g. "0593e2fa-ab5b-4c91-96cb-c9b55c1deb77") to the integer columns in my M2M tables that hold ids for Model A.

Any insight/tips on any of the above would be greatly appreciated! Thank you 🙂

**Comment by maennel** [comment]
Hi @danxshap, thank you for your comment. 
First of all, I'm afraid that the use case to migrate an existing Django model to a CleanerVersion model has not been focused on until now. Thus, there's no logic dedicated to facilitate this. You probably will have to write your own migration logic, adding UUID fields, changing the primary key field etc.

The ``VERSIONS_USE_UUIDFIELD`` property was originally introduced to ease migration from applications running on Django versions older than 1.8, which added support for native UUID-fields ([CleanerVersion docs](https://cleanerversion.readthedocs.io/en/latest/doc/historization_with_cleanerversion.html?highlight=migrate#cleanerversion-1-6-0-django-1-8-3), [Django docs](https://docs.djangoproject.com/en/1.8/ref/models/fields/#uuidfield); UUIDs were saved as chars previously, which had an impact on indexing). 

Regarding the M2M issue, I had to dive in a little. But indeed, "mixed" relationships are not supported with the current code (see method at https://github.com/swisscom/cleanerversion/blob/master/versions/fields.py#L176, which returns an intermediate model with two VersionedForeignKeys). A resolution to this problem could be to define an own intermediate model using Django's ``ManyToManyField.through`` property (https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.ManyToManyField.through).

I hope this helps in some way.

**Comment by danxshap** [comment]
@maennel Yes this makes sense and addresses my questions -- hope it's helpful to someone else in the future as well. Thank you!
