### ISSUE TITLE
Test CleanerVersion migration support for Django =< 1.6 (e.g. with South)

### ISSUE THREAD

**Issue by maennel** [swisscom/cleanerversion#26]
Django 1.7 introduced migrations. CleanerVersion has been adapted to support these (in PR #24). 
However, has not been tested whether CleanerVersion on Django 1.6 supports migrations with South.
If it does not, the according fixes should be applied if possible.

Initial note by @jczulian:
"Since Django migration is inherited from South (migration system used before 1.7) I wonder what is happening when using Django 1.6.X together with South? Does South do something similar to Django 1.7? Therefore should we test alongside the Django's version number if South is present and act in the same way as we do when running under Django 1.7"

**Comment by brki** [comment]
Should we drop this issue?  Django 1.6 is no longer supported by the Django project.

**Comment by maennel** [comment]
Agree.
