### ISSUE TITLE
Deletion with related objects

### ISSUE THREAD

**Issue by raphaelm** [swisscom/cleanerversion#42]
The ``VersionedForeignKey`` should do either of those:

* raise a warning if the ``on_delete`` attribute is set, as it has no effect
* implement ``on_delete`` correctly and thus ``Verionable.delete`` should do things as cascade deletion, deletion protection, setting references to ``NULL``, …

**Comment by brki** [comment]
Deletion handling has been merged into master, see docs for how this behaves for Versionable objects.
