### ISSUE TITLE
Django 1.8: Consider using UUIDField

### ISSUE THREAD

**Issue by raphaelm** [swisscom/cleanerversion#47]
Django 1.8 introduces [UUIDField](https://docs.djangoproject.com/en/dev/ref/models/fields/#django.db.models.UUIDField), which should turn out to be a good choice for cleanerversion's primary keys. However, it's very unclear to me whether there might be migration issues (it should work) and how to maintain compatibility to Django <1.8.

**Comment by brki** [comment]
I've started looking into this; it seems like there's a bug in Django at the moment, which made a cleanerversion test fail:

https://code.djangoproject.com/ticket/24912

As for migrations:
A UUIDField on non-PostgreSQL databases is defined as a 32 character CharField; we've currently got it defined as a 36 character CharField (without-hyphen size vs with-hyphen size).  Will have to look into how to do that.

**Comment by maennel** [comment]
Hm, there is the ``VERSIONS_USE_UUIDFIELD`` setting, allowing to use UUIDFields; So, I'm wondering, whether this issue is still of interest? 
From my point of view, we can close it, since UUIDFields are productively used with CleanerVersion for some time now.
Opinions? ;)

**Comment by raphaelm** [comment]
Since I don't use cleanerversion any more, I don't really care, but I agree that this looks fixed.
