### ISSUE TITLE
Admin Integration (a wishlist for someday)

### ISSUE THREAD

**Issue by ezheidtmann** [swisscom/cleanerversion#59]
CleanerVersion does not currently integrate with the Django admin, but it may someday. As suggested in #54, here are some features or behaviors that might be considered when integrating CleanerVersion with the Django admin:

 - Create a new version on every edit (or optionally with "create new version" checkbox on edit form)
 - View only current revisions and/or set the "as_of" date via filter on changelist
 - View all versions of an instance
 - Revert to an old version, perhaps by editing that version

**Comment by peterfarrell** [comment]
I'd love to see something like this.  If the list of "features" in this ticket is what you want, I might be able to see if I have some engineering time to work on it.

**Comment by maennel** [comment]
Hi @peterfarrell, 
thanks for your message. I currently don't have a precise idea of how such an integration with Django admin should look like. The points brought up by @ezheidtmann sound reasonable to me.
For anything else I'll let you come up with something. Probably it's best to sketch a list of some requirements directly in the docs.

As a side note: From experience, relationships usually generate most of the work. I think, this could be valid for this subject as well...
Thanks.

**Comment by peterfarrell** [comment]
@maennel, thanks for your message -- I think I will try in the next few weeks in building something at least basic and we can work from there.

**Comment by boydjohnson** [comment]
Peter has assigned me this task. We have forked CleanerVersion and will post in this ticket as we progress.

**Comment by boydjohnson** [comment]
First push to [GreatBizTools/CleanerVersion](github.com/GreatBizTools/CleanerVersion) was a small change: start of VersionableAdmin class that right now make id and identity read only.

**Comment by peterfarrell** [comment]
Just wanted to let people know that we're getting very close on making a PR for all of this.  We found out that the relationships weren't as much work as we originally expected -- most things worked out of the box.  The only thing we had to figure out was queryset delete because that wasn't implemented in the custom queryset class.

**Comment by maennel** [comment]
Cool! Looking forward to your PR, @peterfarrell.

**Comment by peterfarrell** [comment]
I merely helped outline the features and what not... However, all the hard
work is being done by @boydjohnson.

**Comment by maennel** [comment]
Oh, by the way: there was quite some work done by @brki on queryset deletion - perhaps there's something you could use (didn't go into the details, but saw that the master branch on GreatBizTools is behind in exactly those points)? ...just to let you know @peterfarrell and @boydjohnson.
Thanks!

**Comment by peterfarrell** [comment]
We'll look into it tomorrow by syncing our fork. The delete method was
basically the only thing we had to add to the current code base. Everything
else is brand new code for the admin.
