### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by aaraid** [swisscom/cleanerversion#78]
Im currently working with Django 1.8 and I would like to use the cleanerversion.
Is there any release date for the support?

**Comment by raphaelm** [comment]
For me, it works fine.

**Comment by maennel** [comment]
Hey, I've addressed this in #79. Let me know if you have any feedback for the Django 1.8 support... Thanks! 
-Manuel

**Comment by maennel** [comment]
Hey everyone, Django 1.8 is now officially supported with the 1.5.0 release of CleanerVersion. 
Closing this issue...
