### ISSUE TITLE
Django Admin-integration: Mix management of plain and versionable models

### ISSUE THREAD

**Issue by maennel** [swisscom/cleanerversion#84]
Currently, it is not possible to manage non-versionable models with the Admin-interface integration that comes with CleanerVersion.
Adapt such that it is possible to mix them.

**Comment by boydjohnson** [comment]
I think it is just that I erroneously registered Wine and WineDrinkerHat with VersionedAdmin. When they are registered with ModelAdmin they are available in the admin without save cloning them. Check out my most recent at [boydjohnson/cleanerversion](http://github.com/boydjohnson/cleanerversion).

**Comment by maennel** [comment]
Understand, thanks.
