### ISSUE TITLE
Django-Admin integration: extend history access possibilities

### ISSUE THREAD

**Issue by maennel** [swisscom/cleanerversion#87]
An object's history should also be accessible from non-current versions (via the top-right History button)

**Comment by boydjohnson** [comment]
Adding explanation: If you click on history for a non-current object you get an error that the object doesn't have a change history. History view calls get_object with the object_id parameter. This comes from the URL and is the identity for Versionable objects, but is assumed to be the primary key in Django Admin. This is where the error comes from. In the VersionedAdmin get_object method we call super to get the object at the beginning and that is where the error is happening. We could in the case of history view not call super.get_object but write some code to use the identity. The other ModelAdmin method that deals with history is history_view and that is a more complicated method.

**Comment by boydjohnson** [comment]
I was wrong. I needed to override history_view and now it shows history for each object with the same identity.
