### ISSUE TITLE
Django Admin Integration: Docs that explain usage of VersionedAdmin class

### ISSUE THREAD

**Issue by boydjohnson** [swisscom/cleanerversion#88]
The VersionedAdmin class has custom boolean fields list_display_show_identity, ..._end_date, ..._start_date that can be overwritten in subclasses to have the admin show fewer versioning descriptors. There should be a place in the docs that explains them as well as the admin as a whole. I failed to think of this when making the original pull request. I'll work on it over the next week.

**Comment by maennel** [comment]
This can be closed, I think. Thanks for the PR!
