### ISSUE TITLE
Alternating .restore() on objects that have .clone() called on them produces unexpected results

### ISSUE THREAD

**Issue by boydjohnson** [swisscom/cleanerversion#90]
For example in the terminal:
   
    from versions_tests.models import City
    A = City(name="A")
    A.save()
    B = A.clone()
    B.name = "B"
    B.save()
    A = City.objects.filter(name = "A")
    A.restore()
    B = City.objects.filter(name = "B").get()
    B.restore()
    As = City.objects.filter(name = "A") #There are more than one now as expected
    for a in As:
         print a.is_current #prints out True, False; so one is still current 

And we have two objects with the same identity that are current. Am I using .restore incorrectly?

Has this been encountered before? I was working on integrating .restore into the admin and I thought this seemed wonky.

**Comment by brki** [comment]
You are quite right, that is wonky.  Thanks for providing code to reproduce it!

**Comment by peterfarrell** [comment]
Thank goodness, @boydjohnson and I were seeing strangeness with restore and tracked it down to memory objects having the wrong state. Thanks for fixing it @brki
