### ISSUE TITLE
Django 1.7 incompatibility in will_not_clone in versions/admin.py

### ISSUE THREAD

**Issue by frensjan** [swisscom/cleanerversion#94]
The changes from https://github.com/swisscom/cleanerversion/commit/f64d69e6cd1e4e3fd030c17adbd9112a28ba4418  for ```will_not_clone``` in ```versions/admin.py``` broke compatibility with Django 1.7. The invocation of ```each_context``` in Django 1.7 doesn't have request as argument. See [django/contrib/admin/sites.py on line 264](https://github.com/django/django/blob/stable/1.7.x/django/contrib/admin/sites.py#L264).

**Comment by maennel** [comment]
Hey, @frensjan, thanks for reporting!

**Comment by frensjan** [comment]
@maennel no problem. Hope the PR helps.
