### ISSUE TITLE
Stop backporting fixes / features for unsupported versions (e.g. 1.6)

### ISSUE THREAD

**Issue by brki** [swisscom/cleanerversion#99]
Currently, Django 1.6 has reached end of life.

Should we not create a Django 1.6 branch of CleanerVersion and let it rest in peace?

This would also mean:
- documenting what version of CleanerVersion works with what release of Django
- removing 1.6 dependant code from CleanerVersion to ease development going further
- removing 1.6 from the Travis test environments

Soon enough (early 2016) Django 1.7 will reach end of life; 

I'm suggesting this to avoid, as much as possible, `if VERSION >=` clauses littering the code, and to let code take advantage of new Django APIs without worrying about unsupported Django versions.  It also creates a burden on developers if all Django versions since 1.6 must be supported; this burden increases with every release.

**Comment by brki** [comment]
@boydjohnson this might be an interesting subject for you?  You asked about continuing 1.6 support at some point.

**Comment by boydjohnson** [comment]
@brki It is totally fine for me to not have 1.6 support. I had wondered in the past since Django had stopped 1.6 support if it would be a good idea to stop 1.6 support with CleanerVersion.

**Comment by peterfarrell** [comment]
I agree with @boydjohnson -- there is no need to support Django 1.6 any longer especially since it appears the release cycle of Django will be increasing to a faster pace . We should document what was the last version number of CleanerVersion that supported 1.6 for those still using 1.6 (so they don't upgrade by accident).

**Comment by brki** [comment]
TODO: create cleanerversion-django1.6 and cleanerversion-django1.7 branches, and cleanup old code branches that support those versions.

**Comment by maennel** [comment]
With the latest PRs addressing Django 1.9 and up, I think we can close this issue. Historic versions of CleanerVersion are tracked using the DJANGO_* branches, indicating the compatibility.
